### ISSUE TITLE
This function does not return anything

### ISSUE THREAD

**Issue by picccard** [Akvanvig/Java-vinger#1]
https://github.com/Akvanvig/Java-vinger/blob/d42b49b9ca4f2a88bdcc81b8cc278f08f4167dc5/IINI4018%20Videreg%C3%A5ende%20prog%20java/%C3%B8ving1/Bord.java#L26-L33

**Comment by Akvanvig** [comment]
Very nice, good eye

**Comment by Akvanvig** [comment]
edit: 1#¤
